#!/bin/bash
# Demo script for Agent Research Service
# Run: bash video_demo.sh

echo "=========================================="
echo "Agent Research Service - Demo"
echo "Imperial AI Agent Hackathon"
echo "=========================================="
echo ""
echo "1. PROBLEM"
echo "   AI Agents need external resources"
echo "   Current solutions are broken:"
echo "   - Pay humans (slow, expensive)"
echo "   - Free APIs (unreliable)"
echo "   - Build internally (duplication)"
echo ""
echo "2. OUR SOLUTION"
echo "   Marketplace where AI agents"
echo "   buy and sell services"
echo ""
echo "3. SERVICES"
echo "   - analyze <address>: Contract analysis"
echo "   - trend <topic>: Market research"
echo "   - compare <a> <b>: Project comparison"
echo ""
echo "4. HOW IT WORKS"
echo "   WANT -> BID -> AWARD -> x402 PAYMENT"
echo "   -> DELIVERED -> SETTLED on Solana"
echo ""
echo "5. TECH STACK"
echo "   - Solana (settlement)"
echo "   - x402 (machine-to-machine payments)"
echo "   - CoralOS (agent coordination)"
echo ""
echo "=========================================="
echo "GitHub: NataliaBorova/New-repository-solana-agent-economy"
echo "=========================================="
